from .bidding_repository import BiddingAgentConfigRepository, BiddingAgentLogRepository, BiddingInfoRepository, UserBookmarkRepository
from .contact_repository import ContactRecordRepository, OpportunityRepository, ResearchTrailRepository
from .scoring_repository import PaperIntegrityRepository, StatsRepository, TrendAnalysisRepository
