"""场景模板，包含预定义的固定场景数据定义。"""

from .scenario_weights import _S, _S2, _S3, _S4, _S5, _S6, _S7, _S8, _S9, _S10, _S11, _S12, _S13

FIXED_SCENARIOS_PART1 = [
    dict(
        title="初次拜访医生",
        role_setting="你是一名医药代表，首次拜访一位三甲医院的心内科主任医师",
        goal="建立良好的第一印象，获取医生初步信任",
        difficulty="easy",
        category="opening",
        content="你第一次拜访这位医生，需要简洁自我介绍并说明拜访目的。医生对医药代表持保留态度。",
        tips="注意开场礼貌，简明扼要，不要急于介绍产品细节，留好后续拜访空间。",
        scoring_weights=_S,
        compliance_points=["禁止夸大产品疗效", "禁止贬低竞品", "禁止未经批准的适应症宣传"],
    ),
    dict(
        title="常规拜访跟进",
        role_setting="你是一名医药代表，例行拜访一位已建立联系的社区卫生中心主任",
        goal="更新产品信息，了解医生近期用药反馈",
        difficulty="easy",
        category="opening",
        content="这是你第三次拜访这位医生，他/她已经处方过你的产品。你需要了解使用反馈并更新最新临床数据。",
        tips="保持专业和谦逊，主动询问使用体验，针对性解答疑问。",
        scoring_weights=_S2,
        compliance_points=["禁止诱导处方", "需客观陈述数据", "禁止利益输送暗示"],
    ),
    dict(
        title="学术拜访",
        role_setting="你是一名医学信息顾问，拜访一家省级医院科室主任进行学术交流",
        goal="通过学术内容建立专业形象，推动学术共识",
        difficulty="medium",
        category="opening",
        content="你携带最新临床研究摘要拜访科室主任，希望就某一治疗领域的最新进展进行学术探讨。",
        tips="以学术讨论为导向，引用权威文献，避免过度商业化的表达。",
        scoring_weights=_S3,
        compliance_points=["学术引用需有据可查", "禁止虚假数据", "禁止诱导处方"],
    ),
    dict(
        title="产品核心信息传递",
        role_setting="你是一名医药代表，向一位内分泌科医生介绍一款新型降糖药物",
        goal="准确传递产品的核心临床数据和适应症信息",
        difficulty="medium",
        category="product_intro",
        content="医生对这类新药了解有限，请你从药物机制、临床疗效、安全性三个方面进行介绍。",
        tips="重点突出循证医学证据，使用客观数据，避免绝对化表述。",
        scoring_weights=_S4,
        compliance_points=["禁止超出说明书的适应症宣传", "引用数据需标注来源", "禁止与其他产品做不当比较"],
    ),
    dict(
        title="竞品对比分析",
        role_setting="你是一名医药代表，医生要求你比较你的产品和市场上同类竞品的差异",
        goal="客观介绍产品差异化优势，同时尊重竞品",
        difficulty="hard",
        category="product_intro",
        content="医生同时在使用竞品，直接要求你说明你的产品相比竞品有什么优势。",
        tips="客观陈述差异化特点，不要直接贬低竞品，以临床数据为支撑。",
        scoring_weights=_S5,
        compliance_points=["禁止贬低竞品", "禁止无依据的功效比较", "需基于头对头研究或真实世界证据"],
    ),
    dict(
        title="真实世界数据解读",
        role_setting="你是一名医学顾问，向一位肿瘤科医生展示产品的真实世界研究数据",
        goal="帮助医生理解真实世界证据的临床意义",
        difficulty="hard",
        category="product_intro",
        content="医生对RWS数据的质量有疑问，质疑其与RCT结果的一致性。你需要解释RWS的价值和局限性。",
        tips="诚实说明RWS与RCT的区别，强调互补关系而非替代关系。",
        scoring_weights=_S6,
        compliance_points=["RWS数据不可与RCT直接比较疗效", "需说明研究设计的局限性", "禁止选择性地报告有利数据"],
    ),
    dict(
        title="价格异议处理",
        role_setting="你是一名医药代表，医生认为你的产品价格过高",
        goal="合理回应价格疑虑，强调产品的 pharmacoeconomic 价值",
        difficulty="medium",
        category="objection",
        content="医生表示你的产品虽然疗效不错，但价格是竞品的两倍，在医保控费压力下难以选择使用。",
        tips="从 pharmacoeconomic 角度分析，强调长期治疗的成本效益，而非单纯价格对比。",
        scoring_weights=_S7,
        compliance_points=["禁止做出价格保证或承诺", "不得暗示回扣或利益", "需基于 pharmacoeconomic 数据"],
    ),
    dict(
        title="疗效异议处理",
        role_setting="你是一名医药代表，医生对产品的疗效数据表示怀疑",
        goal="用循证医学证据消除医生的疗效疑虑",
        difficulty="hard",
        category="objection",
        content="医生阅读了一些质疑你产品疗效的最新文献，对你的产品疗效数据表示不信任。",
        tips="诚实面对文献争议点，提供更全面的证据链，不要回避负面信息。",
        scoring_weights=_S8,
        compliance_points=["禁止隐瞒负面研究结果", "需完整呈现证据全貌", "禁止选择性引用数据"],
    ),
    dict(
        title="安全性异议处理",
        role_setting="你是一名医药代表，医生担心产品的不良反应问题",
        goal="客观说明安全性数据，建立医生对产品安全管理的信心",
        difficulty="medium",
        category="objection",
        content="医生在学术会议上听到关于你的产品可能引起严重不良反应的讨论，表达了对安全性的担忧。",
        tips="不要回避不良反应，提供 AE 数据、发生率和管理方案。",
        scoring_weights=_S9,
        compliance_points=["必须如实报告不良反应数据", "禁止淡化安全风险", "需提供 AE 管理建议"],
    ),
    dict(
        title="竞品优势异议",
        role_setting="你是一名医药代表，医生认为竞品在某方面有明显优势",
        goal="合理应对竞品优势论述，维护产品定位",
        difficulty="hard",
        category="objection",
        content="医生列举了竞品在剂型便捷性、医保覆盖和患者依从性方面的优势，质疑你产品的临床实用性。",
        tips="承认竞品在某些维度的优势，转而强调本品在疗效深度和安全性方面的差异化价值。",
        scoring_weights=_S10,
        compliance_points=["禁止虚假贬低竞品", "需基于事实对比", "禁止误导医生"],
    ),
    dict(
        title="合规话术演练",
        role_setting="你是一名医药代表，模拟在合规框架下向医生进行产品介绍",
        goal="掌握合规推广的核心话术和红线标准",
        difficulty="easy",
        category="compliance",
        content="公司合规部门要求所有代表在限定范围内使用合规话术模板进行产品介绍练习。",
        tips="注意区分合规表述与非合规表述，熟悉公司 SOP 中的合规红线。",
        scoring_weights=_S11,
        compliance_points=["禁止使用绝对化用语", "禁止超出说明书范围", "禁止利益承诺"],
    ),
    dict(
        title="利益冲突处理",
        role_setting="你是一名医药代表，医生暗示希望通过合作获取个人利益",
        goal="在保持良好关系的同时坚守合规底线",
        difficulty="hard",
        category="compliance",
        content="一位长期合作的老客户在交流中暗示，如果公司能提供一些'额外的支持'，他会增加处方量。",
        tips="坚守合规底线，礼貌拒绝不当要求，同时维系正常学术关系。",
        scoring_weights=_S12,
        compliance_points=["禁止利益输送", "禁止变相贿赂", "需符合公司合规政策和 anti-bribery 法规"],
    ),
    dict(
        title="合规边界判断",
        role_setting="你是一名医药代表，需要判断各类场景是否触碰合规红线",
        goal="培养对复杂场景下合规边界的判断能力",
        difficulty="hard",
        category="compliance",
        content="面对一系列实际业务中遇到的边缘情况，判断哪些行为合规、哪些不合规并说明理由。",
        tips="对照行业规范和公司制度进行判断，不确定时以'宁紧勿松'为原则。",
        scoring_weights=_S13,
        compliance_points=["禁止灰色地带操作", "学术赞助须合规透明", "禁止现金或等价物往来"],
    ),
]
