"""initial_schema

Revision ID: 52d4fefec31c
Revises:
Create Date: 2026-06-17 00:43:46.946294

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52d4fefec31c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_vector_memory")
    op.drop_table("compliance_l2_log")
    op.drop_table("federated_nodes")
    op.drop_table("compliance_l3_log")
    op.drop_table("model_compression_jobs")
    op.drop_table("products")
    op.drop_table("enforcement_log")
    op.drop_table("visits")
    op.drop_table("pi_profiles")
    op.drop_table("audit_chain_blocks")
    op.alter_column("admission_records", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_admission_rep"), table_name="admission_records")
    op.drop_index(op.f("idx_admission_status"), table_name="admission_records")
    op.alter_column("agent_brains", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("agent_execution_tasks", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_aet_session"), table_name="agent_execution_tasks")
    op.drop_index(op.f("idx_aet_status"), table_name="agent_execution_tasks")
    op.drop_index(op.f("idx_aet_task"), table_name="agent_execution_tasks")
    op.alter_column("agent_marketplace", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("agent_marketplace", "rating", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.drop_index(op.f("idx_am_cat"), table_name="agent_marketplace")
    op.drop_index(op.f("idx_am_item"), table_name="agent_marketplace")
    op.alter_column("agent_pipelines", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("agent_roles", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "agent_roles", "temperature", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.7)")
    )
    op.drop_index(op.f("idx_agent_roles_type"), table_name="agent_roles")
    op.alter_column("agent_runtime_approvals", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_approvals_status"), table_name="agent_runtime_approvals")
    op.drop_index(op.f("idx_approvals_trace"), table_name="agent_runtime_approvals")
    op.alter_column("agent_runtime_logs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_runtime_logs_agent"), table_name="agent_runtime_logs")
    op.drop_index(op.f("idx_runtime_logs_status"), table_name="agent_runtime_logs")
    op.drop_index(op.f("idx_runtime_logs_trace"), table_name="agent_runtime_logs")
    op.drop_column("agent_runtime_logs", "checkpoint_data")
    op.alter_column("agent_runtime_snapshots", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "agent_runtime_snapshots",
        "created_at",
        existing_type=sa.TIMESTAMP(),
        type_=sa.Text(),
        existing_nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column("agent_runtime_snapshots", "expires_at", existing_type=sa.TIMESTAMP(), type_=sa.Text(), existing_nullable=True)
    op.drop_index(op.f("idx_agent_runtime_snapshots_trace_step"), table_name="agent_runtime_snapshots")
    op.alter_column("agent_skills", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "agent_skills", "confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.drop_index(op.f("idx_ask_entity"), table_name="agent_skills")
    op.drop_index(op.f("idx_ask_role"), table_name="agent_skills")
    op.alter_column("agent_state_snapshots", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_state_snapshots_agent"), table_name="agent_state_snapshots")
    op.drop_index(op.f("idx_state_snapshots_status"), table_name="agent_state_snapshots")
    op.alter_column("api_tokens", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("asr_tasks", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_asr_task_id"), table_name="asr_tasks")
    op.alter_column("async_mdt_opinions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "async_mdt_opinions",
        "confidence",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.drop_index(op.f("idx_async_mdt_contributor"), table_name="async_mdt_opinions")
    op.drop_index(op.f("idx_async_mdt_decision"), table_name="async_mdt_opinions")
    op.alter_column("audit_chain_entries", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_chain_action"), table_name="audit_chain_entries")
    op.drop_index(op.f("idx_chain_entity"), table_name="audit_chain_entries")
    op.drop_index(op.f("idx_chain_time"), table_name="audit_chain_entries")
    op.alter_column("audit_logs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_audit_action_time"), table_name="audit_logs")
    op.drop_index(op.f("idx_audit_entity"), table_name="audit_logs")
    op.drop_index(op.f("idx_audit_user"), table_name="audit_logs")
    op.alter_column("benchmark_reports", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_br_report"), table_name="benchmark_reports")
    op.alter_column("board_tasks", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_board_tasks_assignee"), table_name="board_tasks")
    op.drop_index(op.f("idx_board_tasks_board"), table_name="board_tasks")
    op.alter_column("causal_analyses", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_causal_case"), table_name="causal_analyses")
    op.alter_column("causal_graphs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_cg_decision"), table_name="causal_graphs")
    op.drop_index(op.f("idx_cg_graph"), table_name="causal_graphs")
    op.alter_column("collaboration_sessions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_cs_session"), table_name="collaboration_sessions")
    op.drop_index(op.f("idx_cs_status"), table_name="collaboration_sessions")
    op.alter_column("collaboration_steps", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_cstep_session"), table_name="collaboration_steps")
    op.alter_column("compliance_audit_records", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "compliance_audit_records",
        "score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.drop_index(op.f("idx_audit_records_risk"), table_name="compliance_audit_records")
    op.drop_index(op.f("idx_audit_records_time"), table_name="compliance_audit_records")
    op.drop_index(op.f("idx_audit_records_type"), table_name="compliance_audit_records")
    op.alter_column("compliance_rules", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("compliance_rules", "max_value", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("contents", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("contents", "compliance_score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("counterfactual_scenarios", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("counterfactual_scenarios", "confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.drop_index(op.f("idx_cs_scenario"), table_name="counterfactual_scenarios")
    op.alter_column("cross_case_insights", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "cross_case_insights",
        "confidence",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.drop_index(op.f("idx_insights_confidence"), table_name="cross_case_insights")
    op.drop_index(op.f("idx_insights_type"), table_name="cross_case_insights")
    op.alter_column("customer_interactions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_interactions_customer"), table_name="customer_interactions")
    op.drop_index(op.f("idx_interactions_time"), table_name="customer_interactions")
    op.alter_column("customers", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_customers_hospital"), table_name="customers")
    op.drop_index(op.f("idx_customers_name"), table_name="customers")
    op.alter_column("data_masking_rules", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("decision_cases", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "decision_cases", "outcome_score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_dec_cases_outcome"), table_name="decision_cases")
    op.drop_index(op.f("idx_dec_cases_run"), table_name="decision_cases")
    op.alter_column("did_registry", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_did_did"), table_name="did_registry")
    op.drop_index(op.f("idx_did_status"), table_name="did_registry")
    op.alter_column("dp_audit_log", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "dp_audit_log",
        "epsilon_consumed",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "dp_audit_log", "noise_level", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_dpal_did"), table_name="dp_audit_log")
    op.drop_index(op.f("idx_dpal_type"), table_name="dp_audit_log")
    op.alter_column("effect_metrics", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("effect_metrics", "metric_value", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.drop_index(op.f("idx_em_agent"), table_name="effect_metrics")
    op.drop_index(op.f("idx_em_source_sub"), table_name="effect_metrics")
    op.alter_column("episodic_memory", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "episodic_memory", "valence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column(
        "episodic_memory", "intensity", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.drop_index(op.f("idx_em_event"), table_name="episodic_memory")
    op.drop_index(op.f("idx_em_outcome"), table_name="episodic_memory")
    op.drop_index(op.f("idx_em_time"), table_name="episodic_memory")
    op.alter_column("event_bus_definitions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_ebd_source"), table_name="event_bus_definitions")
    op.drop_index(op.f("idx_ebd_type"), table_name="event_bus_definitions")
    op.alter_column("event_bus_messages", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_ebm_corr"), table_name="event_bus_messages")
    op.drop_index(op.f("idx_ebm_status"), table_name="event_bus_messages")
    op.drop_index(op.f("idx_ebm_type"), table_name="event_bus_messages")
    op.alter_column("event_delivery_log", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_edl_msg"), table_name="event_delivery_log")
    op.drop_index(op.f("idx_edl_target"), table_name="event_delivery_log")
    op.alter_column("fed_audit_contributions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "fed_audit_contributions",
        "weight",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(1.0)"),
    )
    op.drop_index(op.f("idx_fed_contributor"), table_name="fed_audit_contributions")
    op.drop_index(op.f("idx_fed_type"), table_name="fed_audit_contributions")
    op.alter_column("federated_rounds", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_fr_round"), table_name="federated_rounds")
    op.drop_index(op.f("idx_fr_type"), table_name="federated_rounds")
    op.alter_column("hcp_interactions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_hcp_int_hcp"), table_name="hcp_interactions")
    op.drop_index(op.f("idx_hcp_int_time"), table_name="hcp_interactions")
    op.alter_column("hcp_profiles", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "hcp_profiles", "prescription_volume", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("0")
    )
    op.alter_column(
        "hcp_profiles", "influence_score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.alter_column(
        "hcp_profiles",
        "digital_engagement",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.drop_index(op.f("idx_hcp_specialty"), table_name="hcp_profiles")
    op.drop_index(op.f("idx_hcp_tier"), table_name="hcp_profiles")
    op.alter_column("hcp_simulations", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "hcp_simulations", "confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.drop_index(op.f("idx_hcp_sim_hcp"), table_name="hcp_simulations")
    op.alter_column("kg_entities", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "kg_entities", "confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.drop_index(op.f("idx_kge_name"), table_name="kg_entities")
    op.drop_index(op.f("idx_kge_type"), table_name="kg_entities")
    op.alter_column("kg_relations", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "kg_relations", "weight", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.alter_column(
        "kg_relations", "confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.drop_index(op.f("idx_kgr_source"), table_name="kg_relations")
    op.drop_index(op.f("idx_kgr_target"), table_name="kg_relations")
    op.drop_index(op.f("idx_kgr_type"), table_name="kg_relations")
    op.alter_column("kg_search_cache", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_kgq_hash"), table_name="kg_search_cache")
    op.alter_column("market_intel_items", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_intel_items_impact"), table_name="market_intel_items")
    op.drop_index(op.f("idx_intel_items_status"), table_name="market_intel_items")
    op.drop_index(op.f("idx_intel_items_time"), table_name="market_intel_items")
    op.drop_index(op.f("idx_intel_items_type"), table_name="market_intel_items")
    op.alter_column("market_intel_sources", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_intel_sources_active"), table_name="market_intel_sources")
    op.drop_index(op.f("idx_intel_sources_type"), table_name="market_intel_sources")
    op.alter_column("mcp_audit_log", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_mcp_audit_at"), table_name="mcp_audit_log")
    op.drop_index(op.f("idx_mcp_audit_tool"), table_name="mcp_audit_log")
    op.drop_index(op.f("idx_mcp_audit_user"), table_name="mcp_audit_log")
    op.alter_column("mcp_tools", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_mcp_name"), table_name="mcp_tools")
    op.alter_column("mdt_opinions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "mdt_opinions", "confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.drop_index(op.f("idx_mdt_opinions_session"), table_name="mdt_opinions")
    op.alter_column("mdt_participants", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "mdt_participants", "vote_weight", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.drop_index(op.f("idx_mdt_participant_session"), table_name="mdt_participants")
    op.alter_column("mdt_sessions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_mdt_status"), table_name="mdt_sessions")
    op.alter_column("memory_associations", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "memory_associations", "weight", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.drop_index(op.f("idx_mema_a"), table_name="memory_associations")
    op.drop_index(op.f("idx_mema_b"), table_name="memory_associations")
    op.alter_column("memory_consolidation_log", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("memory_entries", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "memory_entries", "importance", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.drop_index(op.f("idx_memory_accessed"), table_name="memory_entries")
    op.drop_index(op.f("idx_memory_importance"), table_name="memory_entries")
    op.drop_index(op.f("idx_memory_type"), table_name="memory_entries")
    op.alter_column("memory_gates", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "memory_gates",
        "importance_threshold",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column("memory_recall_log", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("memory_utility_scores", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "memory_utility_scores",
        "utility_score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "access_frequency",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "recency_score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "importance_score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "connectivity_score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "decay_rate",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.drop_index(op.f("idx_mus_decay"), table_name="memory_utility_scores")
    op.drop_index(op.f("idx_mus_score"), table_name="memory_utility_scores")
    op.alter_column("nmpa_compliance_logs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_ncl_log"), table_name="nmpa_compliance_logs")
    op.drop_index(op.f("idx_ncl_type"), table_name="nmpa_compliance_logs")
    op.drop_column("nmpa_compliance_logs", "check_result")
    op.alter_column("node_memory_links", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "node_memory_links",
        "relevance_score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.drop_index(op.f("idx_nml_memory"), table_name="node_memory_links")
    op.drop_index(op.f("idx_nml_node"), table_name="node_memory_links")
    op.alter_column("notification_templates", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("notifications", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_notif_user"), table_name="notifications")
    op.drop_index(op.f("idx_notif_user_time"), table_name="notifications")
    op.alter_column("opportunities", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "opportunities",
        "estimated_value",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "opportunities", "actual_value", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_opps_assigned"), table_name="opportunities")
    op.drop_index(op.f("idx_opps_customer"), table_name="opportunities")
    op.drop_index(op.f("idx_opps_stage"), table_name="opportunities")
    op.alter_column("orchestration_templates", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_ot_name"), table_name="orchestration_templates")
    op.alter_column("pipeline_runs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("pipeline_step_runs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_step_runs_run"), table_name="pipeline_step_runs")
    op.alter_column("pipeline_steps", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_pipeline_steps_order"), table_name="pipeline_steps")
    op.alter_column("privacy_budgets", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "privacy_budgets",
        "epsilon_total",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(1.0)"),
    )
    op.alter_column(
        "privacy_budgets",
        "epsilon_spent",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "privacy_budgets",
        "epsilon_remaining",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(1.0)"),
    )
    op.drop_index(op.f("idx_pb_did"), table_name="privacy_budgets")
    op.alter_column("privacy_compute_jobs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "privacy_compute_jobs",
        "epsilon_used",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "privacy_compute_jobs",
        "noise_level",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.drop_index(op.f("idx_pcj_job"), table_name="privacy_compute_jobs")
    op.drop_index(op.f("idx_pcj_type"), table_name="privacy_compute_jobs")
    op.alter_column("quotation_approvals", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("quotation_approvals", "amount", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False)
    op.alter_column(
        "quotation_approvals",
        "limit_amount",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.drop_index(op.f("idx_qa_status"), table_name="quotation_approvals")
    op.alter_column("recommendations", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "recommendations", "score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_rec_type"), table_name="recommendations")
    op.drop_index(op.f("idx_rec_user"), table_name="recommendations")
    op.alter_column("route_logs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "route_logs", "confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_route_logs_role"), table_name="route_logs")
    op.drop_index(op.f("idx_route_logs_time"), table_name="route_logs")
    op.alter_column("route_rules", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "route_rules", "temperature", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.7)")
    )
    op.drop_index(op.f("idx_route_priority"), table_name="route_rules")
    op.alter_column("route_stats", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "route_stats", "avg_confidence", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column(
        "route_stats", "avg_tokens", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column(
        "route_stats", "avg_latency_ms", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_route_stats_role"), table_name="route_stats")
    op.alter_column("sensor_sessions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_ss_session"), table_name="sensor_sessions")
    op.alter_column("settings", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("sleep_consolidation_logs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "sleep_consolidation_logs",
        "utility_before",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "sleep_consolidation_logs",
        "utility_after",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("soap_decisions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_soap_priority"), table_name="soap_decisions")
    op.drop_index(op.f("idx_soap_status"), table_name="soap_decisions")
    op.alter_column("soap_templates", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("supply_chain_items", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("supply_chain_items", "unit_price", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.drop_index(op.f("idx_sci_item"), table_name="supply_chain_items")
    op.alter_column("system_configs", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("task_boards", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("teams", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("token_blacklist", "token_jti", existing_type=sa.TEXT(), nullable=False)
    op.drop_index(op.f("idx_blacklist_expires"), table_name="token_blacklist")
    op.alter_column("token_budget", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_token_budget_user"), table_name="token_budget")
    op.alter_column("token_usage", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "token_usage", "cost", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_token_usage_user"), table_name="token_usage")
    op.alter_column("training_attributions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "training_attributions",
        "metric_before",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "metric_after",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "change_pct",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "attribution_score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "confidence",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.drop_index(op.f("idx_ta_metric"), table_name="training_attributions")
    op.drop_index(op.f("idx_ta_user"), table_name="training_attributions")
    op.alter_column("training_corrections", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_corrections_audit"), table_name="training_corrections")
    op.drop_index(op.f("idx_corrections_severity"), table_name="training_corrections")
    op.drop_index(op.f("idx_corrections_status"), table_name="training_corrections")
    op.alter_column("training_modules", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "training_modules",
        "passing_score",
        existing_type=sa.REAL(),
        type_=sa.Float(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.7)"),
    )
    op.drop_index(op.f("idx_tm_category"), table_name="training_modules")
    op.drop_index(op.f("idx_tm_difficulty"), table_name="training_modules")
    op.alter_column("training_roi_analysis", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("training_roi_analysis", "training_hours", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "behavior_change_score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "sales_impact", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "cost_savings", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "roi", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.drop_index(op.f("idx_tra_id"), table_name="training_roi_analysis")
    op.alter_column("training_scripts", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("training_scripts", "score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True)
    op.drop_index(op.f("idx_ts_role"), table_name="training_scripts")
    op.drop_index(op.f("idx_ts_script"), table_name="training_scripts")
    op.alter_column("training_sessions", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "training_sessions", "score", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.drop_index(op.f("idx_ts_module"), table_name="training_sessions")
    op.drop_index(op.f("idx_ts_user"), table_name="training_sessions")
    op.alter_column("user_behaviors", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_ub_action"), table_name="user_behaviors")
    op.drop_index(op.f("idx_ub_target"), table_name="user_behaviors")
    op.drop_index(op.f("idx_ub_user"), table_name="user_behaviors")
    op.alter_column("user_profiles", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_up_user"), table_name="user_profiles")
    op.alter_column("user_team", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("users", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column("vc_credentials", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_vc_issuer"), table_name="vc_credentials")
    op.drop_index(op.f("idx_vc_subject"), table_name="vc_credentials")
    op.drop_index(op.f("idx_vc_type"), table_name="vc_credentials")
    op.alter_column("working_memory", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_wm_expires"), table_name="working_memory")
    op.drop_index(op.f("idx_wm_session"), table_name="working_memory")
    op.alter_column("world_tree_nodes", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_tree_parent"), table_name="world_tree_nodes")
    op.drop_index(op.f("idx_tree_path"), table_name="world_tree_nodes")
    op.drop_index(op.f("idx_tree_type"), table_name="world_tree_nodes")
    op.alter_column("world_tree_snapshots", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.drop_index(op.f("idx_snapshot_node"), table_name="world_tree_snapshots")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_snapshot_node"), "world_tree_snapshots", ["node_id"], unique=False)
    op.alter_column("world_tree_snapshots", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_tree_type"), "world_tree_nodes", ["node_type"], unique=False)
    op.create_index(op.f("idx_tree_path"), "world_tree_nodes", ["path"], unique=False)
    op.create_index(op.f("idx_tree_parent"), "world_tree_nodes", ["parent_id"], unique=False)
    op.alter_column("world_tree_nodes", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_wm_session"), "working_memory", ["session_id"], unique=False)
    op.create_index(op.f("idx_wm_expires"), "working_memory", ["expires_at"], unique=False)
    op.alter_column("working_memory", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_vc_type"), "vc_credentials", ["credential_type"], unique=False)
    op.create_index(op.f("idx_vc_subject"), "vc_credentials", ["subject_did"], unique=False)
    op.create_index(op.f("idx_vc_issuer"), "vc_credentials", ["issuer_did"], unique=False)
    op.alter_column("vc_credentials", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("users", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("user_team", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_up_user"), "user_profiles", ["user_id"], unique=1)
    op.alter_column("user_profiles", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ub_user"), "user_behaviors", ["user_id"], unique=False)
    op.create_index(op.f("idx_ub_target"), "user_behaviors", ["target_type"], unique=False)
    op.create_index(op.f("idx_ub_action"), "user_behaviors", ["action_type"], unique=False)
    op.alter_column("user_behaviors", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ts_user"), "training_sessions", ["user_id"], unique=False)
    op.create_index(op.f("idx_ts_module"), "training_sessions", ["module_id"], unique=False)
    op.alter_column(
        "training_sessions", "score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column("training_sessions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ts_script"), "training_scripts", ["script_id"], unique=False)
    op.create_index(op.f("idx_ts_role"), "training_scripts", ["source_agent_role"], unique=False)
    op.alter_column("training_scripts", "score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("training_scripts", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_tra_id"), "training_roi_analysis", ["analysis_id"], unique=False)
    op.alter_column("training_roi_analysis", "roi", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "cost_savings", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "sales_impact", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "behavior_change_score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "training_hours", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("training_roi_analysis", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_tm_difficulty"), "training_modules", ["difficulty"], unique=False)
    op.create_index(op.f("idx_tm_category"), "training_modules", ["category"], unique=False)
    op.alter_column(
        "training_modules",
        "passing_score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.7)"),
    )
    op.alter_column("training_modules", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_corrections_status"), "training_corrections", ["status"], unique=False)
    op.create_index(op.f("idx_corrections_severity"), "training_corrections", ["severity"], unique=False)
    op.create_index(op.f("idx_corrections_audit"), "training_corrections", ["audit_record_id"], unique=False)
    op.alter_column("training_corrections", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ta_user"), "training_attributions", ["user_id"], unique=False)
    op.create_index(op.f("idx_ta_metric"), "training_attributions", ["metric_name"], unique=False)
    op.alter_column(
        "training_attributions",
        "confidence",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "attribution_score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "change_pct",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "metric_after",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "training_attributions",
        "metric_before",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("training_attributions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_token_usage_user"), "token_usage", ["user_id", "model", "usage_date"], unique=False)
    op.alter_column(
        "token_usage", "cost", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column("token_usage", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_token_budget_user"), "token_budget", ["user_id", "model"], unique=False)
    op.alter_column("token_budget", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_blacklist_expires"), "token_blacklist", ["expires_at"], unique=False)
    op.alter_column("token_blacklist", "token_jti", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("teams", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("task_boards", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("system_configs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_sci_item"), "supply_chain_items", ["item_id"], unique=False)
    op.alter_column("supply_chain_items", "unit_price", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("supply_chain_items", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("soap_templates", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_soap_status"), "soap_decisions", ["status"], unique=False)
    op.create_index(op.f("idx_soap_priority"), "soap_decisions", ["priority"], unique=False)
    op.alter_column("soap_decisions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column(
        "sleep_consolidation_logs",
        "utility_after",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "sleep_consolidation_logs",
        "utility_before",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("sleep_consolidation_logs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("settings", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ss_session"), "sensor_sessions", ["session_id"], unique=False)
    op.alter_column("sensor_sessions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_route_stats_role"), "route_stats", ["role_id"], unique=1)
    op.alter_column(
        "route_stats", "avg_latency_ms", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column(
        "route_stats", "avg_tokens", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column(
        "route_stats", "avg_confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column("route_stats", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_route_priority"), "route_rules", ["priority"], unique=False)
    op.alter_column(
        "route_rules", "temperature", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.7)")
    )
    op.alter_column("route_rules", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_route_logs_time"), "route_logs", ["created_at"], unique=False)
    op.create_index(op.f("idx_route_logs_role"), "route_logs", ["assigned_role_id"], unique=False)
    op.alter_column(
        "route_logs", "confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column("route_logs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_rec_user"), "recommendations", ["user_id"], unique=False)
    op.create_index(op.f("idx_rec_type"), "recommendations", ["rec_type"], unique=False)
    op.alter_column(
        "recommendations", "score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column("recommendations", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_qa_status"), "quotation_approvals", ["status"], unique=False)
    op.alter_column(
        "quotation_approvals",
        "limit_amount",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("quotation_approvals", "amount", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=False)
    op.alter_column("quotation_approvals", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_pcj_type"), "privacy_compute_jobs", ["compute_type"], unique=False)
    op.create_index(op.f("idx_pcj_job"), "privacy_compute_jobs", ["job_id"], unique=False)
    op.alter_column(
        "privacy_compute_jobs",
        "noise_level",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "privacy_compute_jobs",
        "epsilon_used",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("privacy_compute_jobs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_pb_did"), "privacy_budgets", ["did"], unique=False)
    op.alter_column(
        "privacy_budgets",
        "epsilon_remaining",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(1.0)"),
    )
    op.alter_column(
        "privacy_budgets",
        "epsilon_spent",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "privacy_budgets",
        "epsilon_total",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(1.0)"),
    )
    op.alter_column("privacy_budgets", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_pipeline_steps_order"), "pipeline_steps", ["pipeline_id", "step_order"], unique=False)
    op.alter_column("pipeline_steps", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_step_runs_run"), "pipeline_step_runs", ["run_id"], unique=False)
    op.alter_column("pipeline_step_runs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("pipeline_runs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ot_name"), "orchestration_templates", ["template_name"], unique=False)
    op.alter_column("orchestration_templates", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_opps_stage"), "opportunities", ["stage"], unique=False)
    op.create_index(op.f("idx_opps_customer"), "opportunities", ["customer_id"], unique=False)
    op.create_index(op.f("idx_opps_assigned"), "opportunities", ["assigned_to"], unique=False)
    op.alter_column(
        "opportunities", "actual_value", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column(
        "opportunities",
        "estimated_value",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("opportunities", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_notif_user_time"), "notifications", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("idx_notif_user"), "notifications", ["user_id", "is_read"], unique=False)
    op.alter_column("notifications", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("notification_templates", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_nml_node"), "node_memory_links", ["node_id"], unique=False)
    op.create_index(op.f("idx_nml_memory"), "node_memory_links", ["memory_entry_id"], unique=False)
    op.alter_column(
        "node_memory_links",
        "relevance_score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column("node_memory_links", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.add_column("nmpa_compliance_logs", sa.Column("check_result", sa.TEXT(), server_default=sa.text('("pass")'), nullable=True))
    op.create_index(op.f("idx_ncl_type"), "nmpa_compliance_logs", ["document_type"], unique=False)
    op.create_index(op.f("idx_ncl_log"), "nmpa_compliance_logs", ["log_id"], unique=False)
    op.alter_column("nmpa_compliance_logs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_mus_score"), "memory_utility_scores", ["utility_score"], unique=False)
    op.create_index(op.f("idx_mus_decay"), "memory_utility_scores", ["decay_rate"], unique=False)
    op.alter_column(
        "memory_utility_scores",
        "decay_rate",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "connectivity_score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "importance_score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "recency_score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "access_frequency",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column(
        "memory_utility_scores",
        "utility_score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("memory_utility_scores", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("memory_recall_log", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column(
        "memory_gates",
        "importance_threshold",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column("memory_gates", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_memory_type"), "memory_entries", ["memory_type"], unique=False)
    op.create_index(op.f("idx_memory_importance"), "memory_entries", ["importance"], unique=False)
    op.create_index(op.f("idx_memory_accessed"), "memory_entries", ["last_accessed"], unique=False)
    op.alter_column(
        "memory_entries", "importance", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.alter_column("memory_entries", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("memory_consolidation_log", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_mema_b"), "memory_associations", ["memory_id_b"], unique=False)
    op.create_index(op.f("idx_mema_a"), "memory_associations", ["memory_id_a"], unique=False)
    op.alter_column(
        "memory_associations", "weight", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.alter_column("memory_associations", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_mdt_status"), "mdt_sessions", ["status"], unique=False)
    op.alter_column("mdt_sessions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_mdt_participant_session"), "mdt_participants", ["session_id"], unique=False)
    op.alter_column(
        "mdt_participants", "vote_weight", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.alter_column("mdt_participants", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_mdt_opinions_session"), "mdt_opinions", ["session_id"], unique=False)
    op.alter_column(
        "mdt_opinions", "confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.alter_column("mdt_opinions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_mcp_name"), "mcp_tools", ["tool_name"], unique=False)
    op.alter_column("mcp_tools", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_mcp_audit_user"), "mcp_audit_log", ["user_id"], unique=False)
    op.create_index(op.f("idx_mcp_audit_tool"), "mcp_audit_log", ["tool_name"], unique=False)
    op.create_index(op.f("idx_mcp_audit_at"), "mcp_audit_log", ["created_at"], unique=False)
    op.alter_column("mcp_audit_log", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_intel_sources_type"), "market_intel_sources", ["source_type"], unique=False)
    op.create_index(op.f("idx_intel_sources_active"), "market_intel_sources", ["is_active"], unique=False)
    op.alter_column("market_intel_sources", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_intel_items_type"), "market_intel_items", ["item_type"], unique=False)
    op.create_index(op.f("idx_intel_items_time"), "market_intel_items", ["collected_at"], unique=False)
    op.create_index(op.f("idx_intel_items_status"), "market_intel_items", ["status"], unique=False)
    op.create_index(op.f("idx_intel_items_impact"), "market_intel_items", ["impact_level"], unique=False)
    op.alter_column("market_intel_items", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_kgq_hash"), "kg_search_cache", ["query_hash"], unique=False)
    op.alter_column("kg_search_cache", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_kgr_type"), "kg_relations", ["relation_type"], unique=False)
    op.create_index(op.f("idx_kgr_target"), "kg_relations", ["target_entity_id"], unique=False)
    op.create_index(op.f("idx_kgr_source"), "kg_relations", ["source_entity_id"], unique=False)
    op.alter_column(
        "kg_relations", "confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.alter_column(
        "kg_relations", "weight", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.alter_column("kg_relations", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_kge_type"), "kg_entities", ["entity_type"], unique=False)
    op.create_index(op.f("idx_kge_name"), "kg_entities", ["name"], unique=False)
    op.alter_column(
        "kg_entities", "confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(1.0)")
    )
    op.alter_column("kg_entities", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_hcp_sim_hcp"), "hcp_simulations", ["hcp_id"], unique=False)
    op.alter_column(
        "hcp_simulations", "confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.alter_column("hcp_simulations", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_hcp_tier"), "hcp_profiles", ["tier"], unique=False)
    op.create_index(op.f("idx_hcp_specialty"), "hcp_profiles", ["specialty"], unique=False)
    op.alter_column(
        "hcp_profiles",
        "digital_engagement",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column(
        "hcp_profiles", "influence_score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.alter_column(
        "hcp_profiles", "prescription_volume", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("0")
    )
    op.alter_column("hcp_profiles", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_hcp_int_time"), "hcp_interactions", ["conducted_at"], unique=False)
    op.create_index(op.f("idx_hcp_int_hcp"), "hcp_interactions", ["hcp_id"], unique=False)
    op.alter_column("hcp_interactions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_fr_type"), "federated_rounds", ["model_name"], unique=False)
    op.create_index(op.f("idx_fr_round"), "federated_rounds", ["round_id"], unique=False)
    op.alter_column("federated_rounds", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_fed_type"), "fed_audit_contributions", ["contribution_type"], unique=False)
    op.create_index(op.f("idx_fed_contributor"), "fed_audit_contributions", ["contributor_did"], unique=False)
    op.alter_column(
        "fed_audit_contributions",
        "weight",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(1.0)"),
    )
    op.alter_column("fed_audit_contributions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_edl_target"), "event_delivery_log", ["target_end"], unique=False)
    op.create_index(op.f("idx_edl_msg"), "event_delivery_log", ["message_id"], unique=False)
    op.alter_column("event_delivery_log", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ebm_type"), "event_bus_messages", ["event_type"], unique=False)
    op.create_index(op.f("idx_ebm_status"), "event_bus_messages", ["status"], unique=False)
    op.create_index(op.f("idx_ebm_corr"), "event_bus_messages", ["correlation_id"], unique=False)
    op.alter_column("event_bus_messages", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ebd_type"), "event_bus_definitions", ["event_type"], unique=False)
    op.create_index(op.f("idx_ebd_source"), "event_bus_definitions", ["source_end"], unique=False)
    op.alter_column("event_bus_definitions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_em_time"), "episodic_memory", ["created_at"], unique=False)
    op.create_index(op.f("idx_em_outcome"), "episodic_memory", ["outcome"], unique=False)
    op.create_index(op.f("idx_em_event"), "episodic_memory", ["event_type"], unique=False)
    op.alter_column(
        "episodic_memory", "intensity", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.alter_column(
        "episodic_memory", "valence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column("episodic_memory", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_em_source_sub"), "effect_metrics", ["source_sub"], unique=False)
    op.create_index(op.f("idx_em_agent"), "effect_metrics", ["agent_role"], unique=False)
    op.alter_column("effect_metrics", "metric_value", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("effect_metrics", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_dpal_type"), "dp_audit_log", ["operation_type"], unique=False)
    op.create_index(op.f("idx_dpal_did"), "dp_audit_log", ["did"], unique=False)
    op.alter_column(
        "dp_audit_log", "noise_level", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column(
        "dp_audit_log",
        "epsilon_consumed",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("dp_audit_log", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_did_status"), "did_registry", ["status"], unique=False)
    op.create_index(op.f("idx_did_did"), "did_registry", ["did"], unique=False)
    op.alter_column("did_registry", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_dec_cases_run"), "decision_cases", ["pipeline_run_id"], unique=False)
    op.create_index(op.f("idx_dec_cases_outcome"), "decision_cases", ["outcome_score"], unique=False)
    op.alter_column(
        "decision_cases", "outcome_score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.0)")
    )
    op.alter_column("decision_cases", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("data_masking_rules", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_customers_name"), "customers", ["name"], unique=False)
    op.create_index(op.f("idx_customers_hospital"), "customers", ["hospital"], unique=False)
    op.alter_column("customers", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_interactions_time"), "customer_interactions", ["conducted_at"], unique=False)
    op.create_index(op.f("idx_interactions_customer"), "customer_interactions", ["customer_id"], unique=False)
    op.alter_column("customer_interactions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_insights_type"), "cross_case_insights", ["insight_type"], unique=False)
    op.create_index(op.f("idx_insights_confidence"), "cross_case_insights", ["confidence"], unique=False)
    op.alter_column(
        "cross_case_insights",
        "confidence",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column("cross_case_insights", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_cs_scenario"), "counterfactual_scenarios", ["scenario_id"], unique=False)
    op.alter_column("counterfactual_scenarios", "confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("counterfactual_scenarios", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("contents", "compliance_score", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("contents", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("compliance_rules", "max_value", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("compliance_rules", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_audit_records_type"), "compliance_audit_records", ["message_type"], unique=False)
    op.create_index(op.f("idx_audit_records_time"), "compliance_audit_records", ["created_at"], unique=False)
    op.create_index(op.f("idx_audit_records_risk"), "compliance_audit_records", ["risk_level"], unique=False)
    op.alter_column(
        "compliance_audit_records",
        "score",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.0)"),
    )
    op.alter_column("compliance_audit_records", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_cstep_session"), "collaboration_steps", ["session_id"], unique=False)
    op.alter_column("collaboration_steps", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_cs_status"), "collaboration_sessions", ["status"], unique=False)
    op.create_index(op.f("idx_cs_session"), "collaboration_sessions", ["session_id"], unique=False)
    op.alter_column("collaboration_sessions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_cg_graph"), "causal_graphs", ["graph_id"], unique=False)
    op.create_index(op.f("idx_cg_decision"), "causal_graphs", ["decision_id"], unique=False)
    op.alter_column("causal_graphs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_causal_case"), "causal_analyses", ["case_id"], unique=False)
    op.alter_column("causal_analyses", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_board_tasks_board"), "board_tasks", ["board_id", "status"], unique=False)
    op.create_index(op.f("idx_board_tasks_assignee"), "board_tasks", ["assignee_id"], unique=False)
    op.alter_column("board_tasks", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_br_report"), "benchmark_reports", ["report_id"], unique=False)
    op.alter_column("benchmark_reports", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_audit_user"), "audit_logs", ["user_id"], unique=False)
    op.create_index(op.f("idx_audit_entity"), "audit_logs", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("idx_audit_action_time"), "audit_logs", ["action", "created_at"], unique=False)
    op.alter_column("audit_logs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_chain_time"), "audit_chain_entries", ["performed_at"], unique=False)
    op.create_index(op.f("idx_chain_entity"), "audit_chain_entries", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("idx_chain_action"), "audit_chain_entries", ["action"], unique=False)
    op.alter_column("audit_chain_entries", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_async_mdt_decision"), "async_mdt_opinions", ["decision_id"], unique=False)
    op.create_index(op.f("idx_async_mdt_contributor"), "async_mdt_opinions", ["contributor_id"], unique=False)
    op.alter_column(
        "async_mdt_opinions",
        "confidence",
        existing_type=sa.Float(),
        type_=sa.REAL(),
        existing_nullable=True,
        existing_server_default=sa.text("(0.5)"),
    )
    op.alter_column("async_mdt_opinions", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_asr_task_id"), "asr_tasks", ["task_id"], unique=False)
    op.alter_column("asr_tasks", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("api_tokens", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_state_snapshots_status"), "agent_state_snapshots", ["status"], unique=False)
    op.create_index(op.f("idx_state_snapshots_agent"), "agent_state_snapshots", ["agent_id"], unique=False)
    op.alter_column("agent_state_snapshots", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_ask_role"), "agent_skills", ["agent_role"], unique=False)
    op.create_index(op.f("idx_ask_entity"), "agent_skills", ["entity_types"], unique=False)
    op.alter_column(
        "agent_skills", "confidence", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.5)")
    )
    op.alter_column("agent_skills", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_agent_runtime_snapshots_trace_step"), "agent_runtime_snapshots", ["trace_id", "step"], unique=False)
    op.alter_column("agent_runtime_snapshots", "expires_at", existing_type=sa.Text(), type_=sa.TIMESTAMP(), existing_nullable=True)
    op.alter_column(
        "agent_runtime_snapshots",
        "created_at",
        existing_type=sa.Text(),
        type_=sa.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column("agent_runtime_snapshots", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.add_column("agent_runtime_logs", sa.Column("checkpoint_data", sa.TEXT(), server_default=sa.text("(NULL)"), nullable=True))
    op.create_index(op.f("idx_runtime_logs_trace"), "agent_runtime_logs", ["trace_id"], unique=False)
    op.create_index(op.f("idx_runtime_logs_status"), "agent_runtime_logs", ["status"], unique=False)
    op.create_index(op.f("idx_runtime_logs_agent"), "agent_runtime_logs", ["agent_key"], unique=False)
    op.alter_column("agent_runtime_logs", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_approvals_trace"), "agent_runtime_approvals", ["trace_id"], unique=False)
    op.create_index(op.f("idx_approvals_status"), "agent_runtime_approvals", ["status"], unique=False)
    op.alter_column("agent_runtime_approvals", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_agent_roles_type"), "agent_roles", ["role_type"], unique=False)
    op.alter_column(
        "agent_roles", "temperature", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True, existing_server_default=sa.text("(0.7)")
    )
    op.alter_column("agent_roles", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("agent_pipelines", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_am_item"), "agent_marketplace", ["item_id"], unique=False)
    op.create_index(op.f("idx_am_cat"), "agent_marketplace", ["category"], unique=False)
    op.alter_column("agent_marketplace", "rating", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True)
    op.alter_column("agent_marketplace", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_aet_task"), "agent_execution_tasks", ["task_id"], unique=False)
    op.create_index(op.f("idx_aet_status"), "agent_execution_tasks", ["status"], unique=False)
    op.create_index(op.f("idx_aet_session"), "agent_execution_tasks", ["session_id"], unique=False)
    op.alter_column("agent_execution_tasks", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.alter_column("agent_brains", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_index(op.f("idx_admission_status"), "admission_records", ["status"], unique=False)
    op.create_index(op.f("idx_admission_rep"), "admission_records", ["rep_id"], unique=False)
    op.alter_column("admission_records", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.create_table(
        "audit_chain_blocks",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("block_hash", sa.TEXT(), nullable=False),
        sa.Column("prev_block_hash", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("block_data", sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
        sa.Column("block_type", sa.TEXT(), server_default=sa.text("'audit'"), nullable=True),
        sa.Column("created_by", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("node_id", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("timestamp", sa.TEXT(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("block_hash"),
    )
    op.create_table(
        "pi_profiles",
        sa.Column("pi_id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("hcp_id", sa.INTEGER(), nullable=True),
        sa.Column("institution", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.Column("department", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.Column("title", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.Column("research_areas", sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("total_papers", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_grants", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("h_index", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_updated", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.PrimaryKeyConstraint("pi_id"),
    )
    op.create_table(
        "visits",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("hcp_id", sa.INTEGER(), nullable=False),
        sa.Column("hcp_name", sa.TEXT(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("visit_type", sa.TEXT(), server_default=sa.text('("")'), nullable=True),
        sa.Column("evidence_photos", sa.TEXT(), server_default=sa.text('("[]")'), nullable=True),
        sa.Column("location", sa.TEXT(), server_default=sa.text('("")'), nullable=True),
        sa.Column("location_mode", sa.TEXT(), server_default=sa.text('("")'), nullable=True),
        sa.Column("compliance_status", sa.TEXT(), server_default=sa.text('("passed")'), nullable=True),
        sa.Column("created_at", sa.TEXT(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enforcement_log",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("rule_code", sa.TEXT(), nullable=False),
        sa.Column("rule_name", sa.TEXT(), nullable=False),
        sa.Column("severity", sa.TEXT(), nullable=False),
        sa.Column("action", sa.TEXT(), nullable=False),
        sa.Column("visit_data_json", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.INTEGER(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("category", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.Column("brand", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.Column("model", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.Column("spec", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.Column("unit_price", sa.REAL(), server_default=sa.text("(0.0)"), nullable=False),
        sa.Column("keywords", sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("tech_params", sa.TEXT(), server_default=sa.text("'{}'"), nullable=False),
        sa.Column("cert_status", sa.TEXT(), server_default=sa.text("('')"), nullable=False),
        sa.PrimaryKeyConstraint("product_id"),
    )
    op.create_table(
        "model_compression_jobs",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("job_id", sa.TEXT(), nullable=False),
        sa.Column("model_name", sa.TEXT(), nullable=False),
        sa.Column("compression_type", sa.TEXT(), nullable=False),
        sa.Column("original_size_bytes", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("compressed_size_bytes", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("compression_ratio", sa.REAL(), server_default=sa.text("(0.0)"), nullable=False),
        sa.Column("accuracy_impact", sa.REAL(), server_default=sa.text("(0.0)"), nullable=False),
        sa.Column("parameters_before", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("parameters_after", sa.INTEGER(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'pending'"), nullable=False),
        sa.Column("result_detail", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("started_at", sa.TEXT(), nullable=True),
        sa.Column("completed_at", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.TEXT(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_table(
        "compliance_l3_log",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("visit_data_json", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "federated_nodes",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("node_id", sa.TEXT(), nullable=False),
        sa.Column("node_name", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("node_type", sa.TEXT(), server_default=sa.text("'partner'"), nullable=True),
        sa.Column("organization", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
        sa.Column("endpoint_url", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("public_key", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("data_summary", sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
        sa.Column("last_heartbeat", sa.TEXT(), server_default=sa.text("('')"), nullable=True),
        sa.Column("round_count", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("total_samples", sa.INTEGER(), server_default=sa.text("0"), nullable=True),
        sa.Column("reliability_score", sa.REAL(), server_default=sa.text("(0.0)"), nullable=True),
        sa.Column("is_active", sa.INTEGER(), server_default=sa.text("1"), nullable=True),
        sa.Column("registered_at", sa.TEXT(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.Column("updated_at", sa.TEXT(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id"),
    )
    op.create_table(
        "compliance_l2_log",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("rule_id", sa.TEXT(), nullable=False),
        sa.Column("rule_name", sa.TEXT(), nullable=False),
        sa.Column("severity", sa.TEXT(), nullable=False),
        sa.Column("check_type", sa.TEXT(), nullable=False),
        sa.Column("visit_data_json", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_vector_memory",
        sa.Column("id", sa.INTEGER(), nullable=True),
        sa.Column("agent_name", sa.TEXT(), nullable=False),
        sa.Column("key", sa.TEXT(), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("embedding", sa.BLOB(), nullable=True),
        sa.Column("metadata", sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_name", "key"),
    )
    # ### end Alembic commands ###
