# ruff: noqa: F822

import shared.columns as _columns

__all__ = (
    "TABLE_MARKET_INTEL_ITEMS_COLS",
    "TABLE_MARKET_INTEL_SOURCES_COLS",
    "TABLE_ROUTE_LOGS_COLS",
    "TABLE_ROUTE_RULES_COLS",
    "TABLE_ROUTE_STATS_COLS",
    "TABLE_TRAINING_ATTRIBUTIONS_COLS",
    "TABLE_TRAINING_CORRECTIONS_COLS",
    "TABLE_TRAINING_MODULES_COLS",
    "TABLE_TRAINING_ROI_ANALYSIS_COLS",
    "TABLE_TRAINING_SCRIPTS_COLS",
    "TABLE_TRAINING_SESSIONS_COLS",
)

globals().update({name: getattr(_columns, name) for name in __all__})
