"""PI 画像种子数据。"""

from typing import Any

pi_profiles: list[dict[str, Any]] = [
    {
        "id": 1,
        "name": "陈志强",
        "institution": "北京大学肿瘤医院",
        "title": "主任医师",
        "department": "肿瘤内科",
        "h_index": 58,
        "papers": 187,
        "grants": ["国自然重点项目", "国家重点研发计划"],
        "research_areas": ["肿瘤免疫治疗", "靶向治疗", "临床转化"],
        "activity_score": 88,
    },
    {
        "id": 2,
        "name": "刘芳华",
        "institution": "复旦大学附属中山医院",
        "title": "教授",
        "department": "心血管内科",
        "h_index": 45,
        "papers": 156,
        "grants": ["国自然面上项目", "上海市科委项目"],
        "research_areas": ["心血管药理学", "动脉粥样硬化", "脂质代谢"],
        "activity_score": 76,
    },
    {
        "id": 3,
        "name": "王建国",
        "institution": "中国医学科学院",
        "title": "研究员",
        "department": "免疫学",
        "h_index": 62,
        "papers": 203,
        "grants": ["国家杰出青年基金", "国自然重大项目", "科技部863计划"],
        "research_areas": ["免疫检查点", "细胞因子", "肿瘤免疫"],
        "activity_score": 92,
    },
    {
        "id": 4,
        "name": "张明辉",
        "institution": "上海交通大学医学院",
        "title": "教授",
        "department": "神经科学",
        "h_index": 39,
        "papers": 124,
        "grants": ["国自然面上项目", "教育部重点实验室基金"],
        "research_areas": ["神经退行性疾病", "药物递送", "血脑屏障"],
        "activity_score": 65,
    },
    {
        "id": 5,
        "name": "李秀芝",
        "institution": "北京协和医院",
        "title": "主任医师",
        "department": "内分泌科",
        "h_index": 51,
        "papers": 168,
        "grants": ["国自然面上项目", "北京市自然科学基金"],
        "research_areas": ["糖尿病", "代谢性疾病", "内分泌肿瘤"],
        "activity_score": 71,
    },
    {
        "id": 6,
        "name": "赵伟峰",
        "institution": "中山大学肿瘤防治中心",
        "title": "研究员",
        "department": "分子生物学",
        "h_index": 55,
        "papers": 179,
        "grants": ["国家优秀青年基金", "国自然重点项目", "广东省科技计划"],
        "research_areas": ["肿瘤基因组学", "表观遗传学", "精准医疗"],
        "activity_score": 84,
    },
]
